### ISSUE TITLE
wrong file_path in transforms.json

### ISSUE THREAD

**Issue by kf-zhang** [omniobject3d/OmniObject3D#1]
The file_path in blender_render‘s transforms.json is absolute path, maybe it should be updated?

**Comment by wutong16** [comment]
Hello @kf-zhang, thank you for bringing this to our attention! We will update the metadata as soon as possible.

I have just uploaded an example dataset module for your reference. At the moment, you can utilize the image_id (e.g., r_0, r_1) from the metadata and manually assign the path as demonstrated [here](https://github.com/omniobject3d/OmniObject3D/blob/main/tools/blender_dataset.py#LL52C92-L52C92).

**Comment by wutong16** [comment]
Problem fixed!
