### ISSUE TITLE
Questions for the challenges

### ISSUE THREAD

**Issue by SCUTykLin** [omniobject3d/OmniObject3D#11]
Hello
     Can the models used in the challenges be existing work published in other conferences? (CVPR ICCV ECCV ...) Or do you need to propose a model? (Sorry, this is my first time participating in this kind of competition)

**Comment by wutong16** [comment]
Yes! You are allowed to begin with frameworks that have been previously published. However, we encourage participants to add individual modifications, such as novel architectures and innovative training strategies, with the goal of achieving additional improvements.

**Comment by SCUTykLin** [comment]
Thanks for your reply.
