### ISSUE TITLE
Question about the Dateset

### ISSUE THREAD

**Issue by SCUTykLin** [omniobject3d/OmniObject3D#13]
I note that there are only a few scenes in the test set on challenge track 1. Can I use the remaining scenes from the omniobject3D dataset for generalization training?

For example, there are five scenes A, B, C, D, E, and u test our model on scene D. Could I train the model on the A, B, C, E ?

**Comment by wutong16** [comment]
You mean using scenes from the 6k models in the full dataset for training? Of course yes!

**Comment by SCUTykLin** [comment]
ok, Does this mean that the scenes in the test dataset are not in omniobject3D?

**Comment by wutong16** [comment]
Yes. Objects in the test set do not exist in the full dataset that we released.

**Comment by SCUTykLin** [comment]
Thanks for your reply.
