### ISSUE TITLE
Missing Data in Blender Renders

### ISSUE THREAD

**Issue by echen01** [omniobject3d/OmniObject3D#15]
I hope you are doing well. 

I have tried to download the 24-view version of the dataset, and I found missing data. 

In the `raw/blender_renders_24_views/img/laptop/laptop_002` folder, there are only 9 images. It is also missing the `transforms.json` file. 

Thanks!

**Comment by wutong16** [comment]
Sorry for the inconvenience. We have re-rendered `laptop_002`, and you can download it from [here](https://drive.google.com/file/d/1yqg9vrPU1a-oNqL7pUxS1yiO4CNsBjWv/view?usp=drive_link). We will also update it on the platform soon.

**Comment by echen01** [comment]
Thank you for the quick response!
