### ISSUE TITLE
Question for the transform.json

### ISSUE THREAD

**Issue by SCUTykLin** [omniobject3d/OmniObject3D#18]
Hello:
     (1)  Does the meaning of the 'transform_matrix' is the same as the 'transform_matrix' in nerf_synthesis dataset? The format of transform.json is the same.
     (2)  Are near and far 2 and 6, respectively? Here's what the code says. Let me make sure
Thanks!

**Comment by wutong16** [comment]
Hello,
(1) Indeed, they utilize the same format, although the specific camera poses differ.
(2) Yes, you can use [2, 6] as values for [near, far].

**Comment by Mike001-wq** [comment]
> Hello, (1) Indeed, they utilize the same format, although the specific camera poses differ. (2) Yes, you can use [2, 6] as values for [near, far].

Could you please explain the difference between the nerf_synthesis dataset and OmniObject3D in a little more detail?

**Comment by SYSUykLin** [comment]
> > Hello, (1) Indeed, they utilize the same format, although the specific camera poses differ. (2) Yes, you can use [2, 6] as values for [near, far].
> 
> Could you please explain the difference between the nerf_synthesis dataset and OmniObject3D in a little more detail?

I think there is no difference. I can run it with the same parameters of the synthetic dataset.
