### ISSUE TITLE
Camera conventions

### ISSUE THREAD

**Issue by akanimax** [omniobject3d/OmniObject3D#25]
Hello, 

could you please provide information on the camera conventions used with this dataset? I am trying to use this dataset in PyTorch3D, but not getting correct 3D reconstructions even though the cameras look correct in cam-visualisations. 

Best regards,
@akanimax

**Comment by louhz** [comment]
Same Question

**Comment by wutong16** [comment]
Hi. We are using the same format of camera parameters as the NeRF_synthetic dataset, following the OpenGL coordinate system (x: right, y: upward, z: backward), which indeed differs from Pytorch3D's coordinate system. Please find their differences and conventions [here](https://github.com/facebookresearch/pytorch3d/issues/1413).

**Comment by akanimax** [comment]
Hi @wutong16, thanks for the comment. This is super helpful 👍.
