### ISSUE TITLE
camera distance issues associated with render_blender.py

### ISSUE THREAD

**Issue by florinshen** [omniobject3d/OmniObject3D#27]
Hello authors,

I've been attempting to render raw scanned objects using the provided render_blender.py. However, the output images often appear to be scaled incorrectly—either too large or too small.

For a specific example, when rendering the antique_018 object, the resulting RGB image suggests that the camera is positioned too close to the object.

Is there a specific setting or step I might be missing that would adjust this? Any guidance would be greatly appreciated.

Thank you for your assistance!

**Comment by florinshen** [comment]
I use the blender 2.9 LTS for rendering.  And here is the command and output images for rendering antique_018
``` bash
# blender 2.9 LTS
blender -python tools/blender_dataset.py
```
![r_0](https://github.com/omniobject3d/OmniObject3D/assets/44775545/f561cbda-7a89-4240-b17a-371eaaa5819b)
![r_1](https://github.com/omniobject3d/OmniObject3D/assets/44775545/56ce742d-2e3b-458d-a573-8095eaef0626)

**Comment by JQJ001** [comment]
Same question please. Have you solved the problem? @florinshen

**Comment by florinshen** [comment]
all problem solved already. see my forked repo here https://github.com/florinshen/OmniObject3D
