### ISSUE TITLE
How to align the depth map and the given point cloud?

### ISSUE THREAD

**Issue by shangbuhuan13** [omniobject3d/OmniObject3D#28]
Thank you very much for the great dataset!
I am trying to align the given point clouds with the depth map using the 'tranformation.json' file. But I failed to corretly align them using the pin-hole camera model. Do you know where I am wrong? Thanks.
`pc = pc * frame['scale']  # N x 3`
`pose_left = np.array(frame['transform_matrix']) `
`pose_left[:, 1:3] *= -1 `
`R = pose_left[:3, :3] `
`T = pose_left[:3, 3] `
`pc_w = R.transpose() @ pc.transpose() - R.transpose() @ T.reshape(3, 1) `
`x = pc_w[0, :] * camera_intrinsics[0, 0] / pc_w[2, :] + camera_intrinsics[0, 2]`
`y = pc_w[1, :] * camera_intrinsics[1, 1] / pc_w[2, :] + camera_intrinsics[1, 2] `

**Comment by yanditum** [comment]
Problem solved. 
Just need to use the following code to preprocess PC.
pc = pc @ np.asarray([[1, 0, 0], [0, 0, 1], [0, -1, 0]])
