### ISSUE TITLE
Question about raw_scans and  videos_processed alignment

### ISSUE THREAD

**Issue by hugoycj** [omniobject3d/OmniObject3D#29]
Thanks for your great works! 

I have downloaded part of data and found that the mesh in `raw_scans` and sparse point cloud in `videos_processed` is misaligned. I wonder if there exists a alignment matrix to align the two scan such that we could use the mesh for geometry reconstruction evaluation
![Screenshot from 2023-11-19 17-57-28](https://github.com/omniobject3d/OmniObject3D/assets/40767265/01807da4-a8bf-4896-8ef1-cc44c60c34be)

**Comment by wutong16** [comment]
Hi! As of now, we haven't processed the alignment matrix to correlate the raw scans with the videos. Although point cloud registration-based methods can offer a rough alignment, further manual adjustments might be required to ensure a higher precision.
