### ISSUE TITLE
Download command not work

### ISSUE THREAD

**Issue by adkAurora** [omniobject3d/OmniObject3D#34]
after install opendatalab and login, following commands not work ,could you please fix it?

`odl ls     OpenXD-OmniObject3D-New `
`odl get    OpenXD-OmniObject3D-New `

return
```
WARNING:This CLI tool is deprecated and will be removed in a future release.
The opendatalab(odl) pkg has been deprecated and will no longer be supported in few weeks.
We recommend that you switch to the openxlab pkg, which accept same username/password,
provides the same functionality and other enhanced AI friendly features.
More details please refer to https://openxlab.org.cn/datasets

Unable to access. Please visit the dataset homepage!
```

**Comment by wutong16** [comment]
Sorry for the inconvenience. The tool has been updated, and we have also revised the corresponding instructions in the README.md file. Please give it a try!
