### ISSUE TITLE
Cannot download piyata model

### ISSUE THREAD

**Issue by ZhangCYG** [omniobject3d/OmniObject3D#38]
Hello, I met some problems when getting OmniObject3D data. The download process just stops at raw/videos_processed/pitaya.tar.gz, while other files can be got correctly. I've tried several times but every time I have to stop here. How could I solve this?
![image](https://github.com/omniobject3d/OmniObject3D/assets/62829225/44806d6f-ccaa-4a9a-aff1-c580ab57691b)

**Comment by wutong16** [comment]
Hi, could you please attempt to use the following command to download this specific file? It has been successful on my end.
```
openxlab dataset download --dataset-repo OpenXDLab/OmniObject3D-New \
                          --source-path /raw/videos_processed/pitaya.tar.gz \
                          --target-path .
```

**Comment by ZhangCYG** [comment]
The strange thing is, this command fit all other objects except pitaya.
![image](https://github.com/omniobject3d/OmniObject3D/assets/62829225/d24d329c-aa5f-422a-8b12-3e6758a7a241)
I don't know if you can send me pitaya by email or other ways, and I try to continue other objects?

**Comment by wutong16** [comment]
We are also maintaining the dataset on [Google Drive](https://drive.google.com/drive/folders/1-hlkTqUJR_J2xht1qztmX2xAq_qNw4vn?usp=sharing), which is the same as on the original platform. You can find the videos_processed/pitaya.tar.gz [here](https://drive.google.com/file/d/1DWV4X3qMJz_4O3eH1qIA-5pUNfL74Dxu/view?usp=drive_link). Please take a try.

**Comment by ZhangCYG** [comment]
Thank you. After downloading pitaya from Google Drive, I finished the whole dataset downloading. I'm not sure where the problem is though.
