### ISSUE TITLE
Question about 3D Object Generation

### ISSUE THREAD

**Issue by LiyingCV** [omniobject3d/OmniObject3D#4]
Hi, could you release the pretrain model of GET3D training on OmniObject3D? Thanks in advance.

**Comment by wutong16** [comment]
Sorry that we currently do not plan to release the pre-trained models of GET3D, but we will provide the multi-view rendered data in  GET3D's official format along with the instructions on how to run with it soon (within a month).

**Comment by LiyingCV** [comment]
> Sorry that we currently do not plan to release the pre-trained models of GET3D, but we will provide the multi-view rendered data in GET3D's official format along with the instructions on how to run with it soon (within a month).

Thanks!
