### ISSUE TITLE
ModelNet40 corresponding labels

### ISSUE THREAD

**Issue by kmn5409** [omniobject3d/OmniObject3D#7]
Will the full list of objects that were used to calculate the OA<sub>Style</sub> be released, meaning the correspondences between ModelNet40 categories and OmniObject3D categories used to calculate the OA<sub>Style</sub>.

Since there are unclear correspondences like lamp from ModelNet40 corresponding with light from OmniObject3D, I'm not sure about the correspondences. But we would have clearer correspondences like bed from ModelNet40 and bed from OmniObject3D.

**Comment by omniobject3d** [comment]
Sorry for the delayed reply, the overlapped labels include:

bed
bottle
bowl
chair
cup
flower_pot
guitar
keyboard
laptop
light -> lamp
plant
cup
sofa
desk
red_wine_glass -> cup
table (2,3,4,7,23,24,26 -> table; 1,5,8,9,13,14,15,16,17,18,19,20,21,22,25,27,28 -> desk)
toy_car -> car
toy_plane -> airplane
toy_plant -> plant
plant
tv_stand
vase

The category names listed above are all sourced from the latest OmniObject3D dataset. In cases where no specific modifications have been made, they align with the names in the ModelNet40 dataset. The use of "->" signifies instances where a renaming has been applied to match the ModelNet40 dataset's nomenclature.
