### ISSUE TITLE
How to calculate the depth.

### ISSUE THREAD

**Issue by kf-zhang** [omniobject3d/OmniObject3D#8]
The depth is stored as a exr file, but I'm uncertain about whether I need to scale the depth in exr file by the scale in transforms.json file. And what does the scale in transforms.json mean?

**Comment by wutong16** [comment]
Hi, you can directly load the depth from the .exr file without any additional scaling. The `scale` in `transforms.json` denotes the `normalized object size / real-world object size`, and you can find its usage [here](https://github.com/omniobject3d/OmniObject3D/blob/main/tools/mesh_eval.py#L203), which is usually used for the calculation of chamfer distance between a normalized output and the raw scan.
